<?php

namespace ContainerJazIMP6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGreeterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Greeter' shared autowired service.
     *
     * @return \App\Service\Greeter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/Greeter.php';

        return $container->privates['App\\Service\\Greeter'] = new \App\Service\Greeter('sahra');
    }
}
