<?php

namespace ContainerDpWsLqQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_H0QRQneService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.H0QRQne' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.H0QRQne'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'logger' => ['privates', 'App\\Service\\Greeter', 'getGreeterService', true],
        ], [
            'logger' => 'App\\Service\\Greeter',
        ]);
    }
}
