<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYKWX4PE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYKWX4PE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYKWX4PE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYKWX4PE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYKWX4PE\App_KernelDevDebugContainer([
    'container.build_hash' => 'YKWX4PE',
    'container.build_id' => '2e461f8a',
    'container.build_time' => 1598461432,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYKWX4PE');
