<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerI3pjvzV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerI3pjvzV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerI3pjvzV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerI3pjvzV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerI3pjvzV\App_KernelDevDebugContainer([
    'container.build_hash' => 'I3pjvzV',
    'container.build_id' => 'a600f132',
    'container.build_time' => 1598290920,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerI3pjvzV');
